class ActionKind(Enum):
    Walking = 0
    Idle = 1
    Jumping = 2
    walking2 = 3

def on_a_pressed():
    if hero.vy == 0:
        hero.vy = -250
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

hero: Sprite = None
hero = sprites.create(img("""
        ........................
            .....ffff...............
            ...fff22fff.............
            ..fff2222fff............
            .fffeeeeeefff...........
            .ffe222222eef...........
            .fe2ffffff2ef...........
            .ffffeeeeffff...........
            ffefbf44fbfeff..........
            fee41fddf14eef..........
            .ffffdddddeef...........
            fddddf444eef............
            fbbbbf2222f4e...........
            fbbbbf2222fd4...........
            .fccf45544f44...........
            ..ffffffff..............
            ....ff..ff..............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
    """),
    SpriteKind.player)
scene.set_background_color(9)
controller.move_sprite(hero, 80, 0)
scene.camera_follow_sprite(hero)
tiles.set_tilemap(tilemap("""level1"""))
hero.ay = 700
idle = animation.create_animation(ActionKind.Idle, 500)
idle.add_animation_frame(img("""
    ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf2222f4e...........
        fbbbbf2222fd4...........
        .fccf45544f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
"""))
idle.add_animation_frame(img("""
    ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        ..ffffddddeef...........
        .fddddf44eef............
        .fbbbbf2224e............
        .fbbbbf222d4............
        ..fccf554444............
        ...fffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
"""))
idle.add_animation_frame(img("""
    ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf2222f4e...........
        fbbbbf2222fd4...........
        .fccf45544f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
"""))
animation.attach_animation(hero, idle)
walkin = animation.create_animation(ActionKind.Walking, 100)
walkin.add_animation_frame(img("""
    ........................
        ....ffffff..............
        ..ffeeeef2f.............
        .ffeeeef222f............
        .feeeffeeeef............
        .ffffee2222ef...........
        .fe222ffffe2f...........
        fffffffeeeff............
        ffe44ebf44e.............
        fee4d41fdde.............
        .feee4ddded.............
        ..ffee44e4dde...........
        ...f222244ee............
        ...f2222e2f.............
        ...f444455f.............
        ....ffffff..............
        .....fff................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
"""))
walkin.add_animation_frame(img("""
    ........................
        .......fff..............
        ....fffff2f.............
        ..ffeeeee22ff...........
        .ffeeeeee222ff..........
        .feeeefffeeeef..........
        .fffffeee2222ef.........
        fffe222fffffe2f.........
        fffffffffeeefff.........
        fefe44ebbf44eef.........
        .fee4d4bbfddef..........
        ..feee4dddddfee.........
        ...f2222222eedd.........
        ...f444445e44dd.........
        ...ffffffffeeee.........
        ...fff...ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
"""))
animation.attach_animation(hero, walkin)
walkinleft = animation.create_animation(ActionKind.walking2, 100)
walkinleft.add_animation_frame(img("""
    ........................
        ...ffffff...............
        ..f2feeeeff.............
        .f222feeeeff............
        .feeeeffeeef............
        fe2222eeffff............
        f2effff222ef............
        .ffeeefffffff...........
        ..e44fbe44eff...........
        ..eddf14d4eef...........
        ..deddd4eeef............
        edd4e44eeff.............
        .ee442222f..............
        ..f2e2222f..............
        ..f554444f..............
        ...ffffff...............
        .....fff................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
"""))
walkinleft.add_animation_frame(img("""
    ........................
        .....fff................
        ....f2fffff.............
        ..ff22eeeeeff...........
        .ff222eeeeeeff..........
        .feeeefffeeeef..........
        fe2222eeefffff..........
        f2efffff222efff.........
        fffeeefffffffff.........
        fee44fbbe44efef.........
        .feddfbb4d4eef..........
        eefddddd4eeef...........
        ddee2222222f............
        dd44e544444f............
        eeeeffffffff............
        ....ff...fff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
"""))
animation.attach_animation(hero, walkinleft)

def on_on_update():
    if hero.vx > 0:
        animation.set_action(hero, ActionKind.Walking)
    elif hero.vx < 0:
        animation.set_action(hero, ActionKind.walking2)
    else:
        animation.set_action(hero, ActionKind.Idle)
game.on_update(on_on_update)
